# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bartab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser',
            name='tab',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
