# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bartab', '0002_adduser_tab'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addItem',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='addUser',
            new_name='User',
        ),
    ]
